# Generated by Django 2.1.5 on 2019-02-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
        ('studyguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=6)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='studyguide.CourseType')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='timeline.Year')),
            ],
        ),
        migrations.AddField(
            model_name='masterprogram',
            name='MainCourses',
            field=models.ManyToManyField(related_name='programs', to='studyguide.MainCourse'),
        ),
    ]
