# Generated by Django 2.1.5 on 2019-02-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.Project')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Student'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='students.Application')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='projects.Project')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Student'],
            },
        ),
    ]
