# Generated by Django 2.1.5 on 2019-02-16 11:05

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(blank=True, max_length=200, null=True)),
                ('OriginalName', models.CharField(blank=True, max_length=200, null=True)),
                ('File', models.FileField(default=None, upload_to=students.models.StudentFile.make_upload_path)),
                ('TimeStamp', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.Distribution')),
            ],
        ),
    ]
