# Generated by Django 2.1.5 on 2019-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ExternalStaff',
            field=models.TextField(blank=True, help_text='External staff (for instance company contact person). Please put one name and/or email on each line.', null=True),
        ),
    ]
