# Generated by Django 2.1.3 on 2019-06-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_externalstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studyguide.CapacityGroup'),
        ),
    ]
