# Generated by Django 2.2.2 on 2019-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190628_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='GeneralDescription',
            field=models.TextField(help_text='General description of the project. Hyperlinks will be tested before publishing.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='StudentsTaskDescription',
            field=models.TextField(help_text='Task description of the project. Hyperlinks will be tested before publishing.'),
        ),
    ]
