# Generated by Django 2.1.3 on 2019-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyguide', '0007_remove_masterprogram_courses'),
        ('projects', '0004_auto_20190701_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='RecommendedCourses',
            field=models.ManyToManyField(blank=True, help_text='Courses recommended to be able to do this project. Leave the field blank if there are no recommended courses.', related_name='projects', to='studyguide.MainCourse'),
        ),
    ]
