# Generated by Django 2.1.3 on 2019-07-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_recommendedcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='RequiredCourses',
        ),
    ]
