# Generated by Django 2.1.5 on 2019-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Begin', models.DateField()),
                ('End', models.DateField()),
            ],
            options={
                'ordering': ['Begin'],
            },
        ),
    ]
