# Generated by Django 2.1.5 on 2019-02-16 10:39

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studyguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=15)),
                ('Text', models.CharField(max_length=512)),
                ('File', models.ImageField(blank=True, default=None, null=True, upload_to=support.models.Promotion.make_upload_path)),
                ('Visible', models.BooleanField(default=True)),
                ('Url', models.URLField(blank=True, default=None, null=True)),
                ('CapacityGroups', models.ManyToManyField(blank=True, default=None, related_name='promotions', to='studyguide.CapacityGroup')),
            ],
        ),
    ]
