# Generated by Django 2.1.3 on 2019-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mailing',
            name='TimeStamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
