# Generated by Django 2.1.5 on 2019-02-16 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cohort', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('Origin', models.CharField(choices=[('bsc_ee_tue', 'BSc EE TU/e'), ('bsc_au_tue', 'BSc AU TU/e'), ('bsc_ele_other', 'BSc EE Other'), ('sense', 'SENSE (Smart Electrical Networks and Systems)'), ('premaster_hbo_tue', 'Premaster HBO TU/e'), ('premaster_other', 'Premaster Other'), ('other', 'Other institute')], max_length=32)),
                ('Institute', models.CharField(blank=True, max_length=256, null=True)),
                ('OutOfFacultyCourses', models.TextField(blank=True, null=True)),
                ('Approved', models.BooleanField(default=False)),
                ('Electives', models.ManyToManyField(blank=True, related_name='registrations', to='studyguide.Course')),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='studyguide.MasterProgram')),
                ('Student', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stamp', models.DateField()),
                ('Type', models.IntegerField(choices=[(1, 'First'), (2, 'Second')], unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDeadlineDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
