# Generated by Django 2.1.5 on 2019-02-18 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=16)),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Quartile', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Approved',
        ),
        migrations.AddField(
            model_name='registration',
            name='State',
            field=models.IntegerField(choices=[(1, 'Student filling in'), (2, 'Submitted for approval'), (3, 'Approved')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning',
            name='Registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courseplanning', to='registration.Registration'),
        ),
        migrations.AddField(
            model_name='plannedcourse',
            name='Planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='registration.Planning'),
        ),
    ]
