# Generated by Django 2.1.3 on 2019-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190218_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='State',
            field=models.IntegerField(choices=[(1, 'Student filling in'), (2, 'Submitted for approval'), (3, 'Approved')], default=1),
        ),
    ]
