# Generated by Django 2.1.3 on 2019-06-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190223_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='studyguide.MasterProgram'),
        ),
    ]
