# Generated by Django 2.1.5 on 2019-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(choices=[(0, 'students'), (1, 'studyadvisors'), (2, 'supervisors'), (3, 'assistants')], default=0)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Cohort', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
