# Generated by Django 2.1.5 on 2019-02-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesscontrol', '0001_initial'),
        ('studyguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='Groups',
            field=models.ManyToManyField(to='studyguide.CapacityGroup'),
        ),
        migrations.AddField(
            model_name='allowedaccess',
            name='Origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accesscontrol.Origin'),
        ),
        migrations.AddField(
            model_name='allowedaccess',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
