# Generated by Django 2.1.3 on 2019-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0003_remove_allowedaccess_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='Groups',
            field=models.ManyToManyField(help_text='Students of this origin can view projects of the selected capacity groups.', to='studyguide.CapacityGroup'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='Name',
            field=models.CharField(help_text='Name of the origin. Name ELE is reserved.', max_length=256, unique=True),
        ),
    ]
