# Generated by Django 2.1.5 on 2019-06-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0004_auto_20190319_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrantStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Level', models.IntegerField(choices=[(1, 'SuperVisor'), (2, 'Assistants')], default=1)),
            ],
        ),
    ]
