# Generated by Django 2.1.3 on 2019-06-28 13:11

from django.db import migrations, models
import django.db.models.deletion
import timeline.utils


class Migration(migrations.Migration):

    dependencies = [
        ('studyguide', '0004_masterprogramimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprogram',
            name='Year',
            field=models.ForeignKey(default=timeline.utils.get_year_id, on_delete=django.db.models.deletion.PROTECT, to='timeline.Year'),
        ),
    ]
