# Generated by Django 2.1.3 on 2019-07-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyguide', '0006_auto_20190701_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprogram',
            name='Courses',
        ),
    ]
