# Generated by Django 2.1.3 on 2019-07-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyguide', '0007_remove_masterprogram_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='TargetAudience',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Year',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
